# Generated by Django 5.2.4 on 2025-07-12 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdesaoLojista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        help_text="ex. 00.000.000/0000-00",
                        max_length=18,
                        null=True,
                        unique=True,
                        verbose_name="Cnpj do Lojista",
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Razão Social"
                    ),
                ),
                (
                    "fantasia",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Nome Fantasia"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=250, null=True, verbose_name="Email"),
                ),
                (
                    "telefone",
                    models.CharField(
                        help_text="(xx) xxxxx - xxxx",
                        max_length=20,
                        null=True,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "data_contato",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora em que o vendedor entrou em contato ",
                        null=True,
                        verbose_name="Data do contato",
                    ),
                ),
                ("atendido", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Sim", "Sim"),
                            ("Inativo", "Inativo"),
                            ("Atendido sem Venda", "Atendido sem Venda"),
                            ("Nao Atendido", "Não Atendido"),
                        ],
                        default="Pendente",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "atendido_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Atendido por",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "autorizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_modificado_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Adesão de Lojista",
                "verbose_name_plural": "Adesões de Lojistas",
            },
        ),
        migrations.CreateModel(
            name="Localizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=250)),
                ("descricao", models.TextField(blank=True)),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cadastrado Por",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RamoAtividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atividade",
                    models.CharField(
                        help_text="Informe o Ramo de Atividade. (exemplo: alimentação, vestuário, restaurante, etc.)",
                        max_length=80,
                    ),
                ),
                (
                    "dataCadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Cadastrado em"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cadastrado Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "ramo de Atividade",
                "verbose_name_plural": "ramos de Atividades",
                "ordering": ["atividade"],
            },
        ),
        migrations.CreateModel(
            name="Lojista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CNPJLojista",
                    models.CharField(
                        help_text="ex. 00.000.000/0000-00",
                        max_length=18,
                        null=True,
                        unique=True,
                        verbose_name="CNPJ do Lojista*",
                    ),
                ),
                (
                    "IELojista",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        verbose_name="Inscrição Estadual",
                    ),
                ),
                (
                    "razaoLojista",
                    models.CharField(
                        blank=True,
                        help_text="Razão Social",
                        max_length=200,
                        null=True,
                        verbose_name="Razão Social*",
                    ),
                ),
                (
                    "fantasiaLojista",
                    models.CharField(
                        help_text="Nome Fantasia",
                        max_length=200,
                        verbose_name="Nome Fantasia*",
                    ),
                ),
                (
                    "dataCadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Cadastrado em"
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Endereço"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        help_text="ex. (85)3212-0000",
                        max_length=150,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Sim", "Sim"),
                            ("Não", "Não"),
                            ("Inativo", "Inativo"),
                        ],
                        default="Pendente",
                        max_length=20,
                    ),
                ),
                (
                    "lojista_cielo",
                    models.BooleanField(default=False, verbose_name="Lojista Cielo"),
                ),
                (
                    "autorizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lojistas_autorizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autorizado por",
                    ),
                ),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lojistas_cadastrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cadastrado Por",
                    ),
                ),
                (
                    "localizacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lojista.localizacao",
                    ),
                ),
                (
                    "ramoAtividade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lojista.ramoatividade",
                        verbose_name="Ramo de Atividade*",
                    ),
                ),
            ],
            options={
                "verbose_name": "lojista",
                "verbose_name_plural": "lojistas",
                "ordering": ["fantasiaLojista"],
            },
        ),
    ]
