# Generated by Django 5.2.4 on 2025-08-10 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lojista", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutorizacaoLojista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_anterior", models.CharField(blank=True, max_length=20)),
                ("status_novo", models.CharField(max_length=20)),
                ("data_autorizacao", models.DateTimeField(auto_now_add=True)),
                ("observacao", models.TextField(blank=True)),
                (
                    "autorizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autorizacoes_feitas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lojista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autorizacoes",
                        to="lojista.lojista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autorização de Lojista",
                "verbose_name_plural": "Autorizações de Lojistas",
                "ordering": ["-data_autorizacao"],
            },
        ),
    ]
