# Generated by Django 5.2.4 on 2025-07-12 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("participante", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cupom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataCriacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Cadastrado em"
                    ),
                ),
                ("impresso", models.BooleanField(default=False)),
                ("dataImpressao", models.DateTimeField(blank=True, null=True)),
                ("reimpresso_em", models.DateTimeField(blank=True, null=True)),
                (
                    "documentoFiscal",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rel_cupom_doc",
                        to="participante.documentofiscal",
                    ),
                ),
                (
                    "operador",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rel_cupom_operador",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cadastrado Por",
                    ),
                ),
                (
                    "posto_trabalho",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="participante.postotrabalho",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rel_cupom_participante",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
