# Generated by Django 5.2.4 on 2025-07-18 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cupom", "0001_initial"),
        ("participante", "0002_roles_and_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cupom",
            options={"verbose_name": "Cupom", "verbose_name_plural": "Cupons"},
        ),
        migrations.RemoveField(
            model_name="cupom",
            name="posto_trabalho",
        ),
        migrations.AddField(
            model_name="cupom",
            name="em_impressao",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cupom",
            name="falhas_impressao",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cupom",
            name="tentativa_impressao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cupom",
            name="dataCriacao",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="cupom",
            name="documentoFiscal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rel_cupom_doc",
                to="participante.documentofiscal",
            ),
        ),
        migrations.AlterField(
            model_name="cupom",
            name="operador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rel_operador",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cupom",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rel_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
