# Generated by Django 5.2.4 on 2025-07-20 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cupom", "0002_add_print_tracking_fields"),
        ("participante", "0004_campanha_banner_hero_campanha_cor_hover_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cupom",
            name="posto_trabalho",
            field=models.ForeignKey(
                blank=True,
                help_text="Local onde o cupom foi impresso",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="participante.postotrabalho",
                verbose_name="Posto onde foi impresso",
            ),
        ),
    ]
