# Generated by Django 4.2.23 on 2025-09-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PessoaOrganizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "cpf",
                    models.CharField(
                        help_text="000.000.000-00", max_length=14, unique=True
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("CDL", "CDL"),
                            ("SOLVE", "Solve"),
                            ("OUTROS", "Outros"),
                        ],
                        default="CDL",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pessoa da Organização",
                "verbose_name_plural": "Pessoas da Organização",
                "ordering": ["nome"],
                "indexes": [
                    models.Index(fields=["cpf"], name="organizacao_cpf_fb9521_idx"),
                    models.Index(
                        fields=["origem"], name="organizacao_origem_6f8503_idx"
                    ),
                ],
            },
        ),
    ]
