# Generated by Django 4.2.23 on 2025-09-04 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cupom", "0003_cupom_posto_trabalho"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SorteioResultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.CharField(max_length=14)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("valido", models.BooleanField(default=True)),
                ("motivo_invalidacao", models.CharField(blank=True, max_length=255)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sorteios_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cupom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados_sorteio",
                        to="cupom.cupom",
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sorteios_vencidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de Sorteio",
                "verbose_name_plural": "Resultados de Sorteio",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddConstraint(
            model_name="sorteioresultado",
            constraint=models.UniqueConstraint(
                fields=("cupom",), name="unique_resultado_por_cupom"
            ),
        ),
    ]
