# Pacote de views gerado automaticamente por refatoracao

from .utils import (
    can_manage_journey_records,
    solicitar_materiais,
)
from .cupom import (
    reprint,
    cupons,
    search_cupom,
    search,
)
from .lojista import (
    autorizar_lojista,
    gerenciar_lojistas,
    editar_lojista,
    homepage,
    lojistas_home,
    cadastro_lojista,
    edit,
    editlojista,
    lojistalist,
    autorizar_lojistas,
    buscar_lojista_ajax,
    cadastrar_lojista_ajax,
)
from .posto_localizacao import (
    registeratividade,
    register_localizacao,
    listatividade,
    editar_ramo_atividade,
    excluir_ramo_atividade,
    lista_localizacao,
    editar_localizacao,
    excluir_localizacao,
    lista_interessado,
    marcar_como_atendido,
    register_posto,
    listar_postos,
    editar_posto,
    excluir_posto,
    atualizar_status,
    buscar_ramos_atividade_ajax,
    buscar_localizacoes_ajax,
)
from .colaborador import (
    cadastrar_colaborador,
    gerenciar_colaboradores_pendentes,
    cadastrar_colaboradores_massa,
    upload_colaboradores_lote,
    cadastrar_colaborador_rapido,
    criar_url_treinamento,
    gerenciar_urls_treinamento,
    colaboradores_url_treinamento,
    gestao_colaboradores_dashboard,
    configurar_colaborador_unificado,
)
from .jornada import (
    jornadas_gestao,
    tipos_jornada_list,
    tipo_jornada_create,
    tipo_jornada_edit,
    jornadas_colaboradores_list,
    jornada_colaborador_create,
    jornada_colaborador_edit,
    jornada_colaborador_toggle_status,
    configuracoes_jornada_list,
    configuracao_jornada_create,
    configuracao_jornada_edit,
    configuracao_jornada_toggle_status,
    excecoes_jornada_list,
    excecao_jornada_create,
    excecao_jornada_edit,
    excecao_jornada_toggle_status,
    finalizar_jornadas_automaticas_manual,
    gestao_registros_jornada,
    editar_registro_jornada,
    finalizar_jornadas_esquecidas,
    exportar_registros_jornada_pdf,
)
