# Generated by Django 5.2.4 on 2025-07-12 00:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import participante.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lojista", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostoTrabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=250)),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Campanha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=250)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("instagram", models.CharField(max_length=250, null=True)),
                ("site", models.CharField(max_length=250, null=True)),
                ("whatsapp", models.CharField(max_length=250, null=True)),
                ("criada_em", models.DateTimeField(auto_now=True)),
                ("finalizada_em", models.DateTimeField(blank=True, null=True)),
                ("ativa", models.BooleanField(default=True)),
                (
                    "finalizada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registro_campanha",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [("finalizar_campanha", "Pode finalizar a campanha")],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("photo", models.ImageField(blank=True, upload_to="users/%Y/%m/%d")),
                ("nome", models.CharField(blank=True, max_length=100)),
                ("RG", models.CharField(blank=True, max_length=40)),
                ("CPF", models.CharField(blank=True, max_length=14, unique=True)),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Feminino"),
                            ("P", "Prefiro não dizer"),
                        ],
                        help_text="ex. M ou F ou P",
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "foneFixo",
                    models.CharField(
                        blank=True,
                        help_text="ex. (85)3212-0000",
                        max_length=15,
                        verbose_name="Telefone Fixo",
                    ),
                ),
                (
                    "foneCelular1",
                    models.CharField(
                        blank=True,
                        help_text="ex. (85)98888-8675",
                        max_length=15,
                        verbose_name="Celular1",
                    ),
                ),
                (
                    "foneCelular2",
                    models.CharField(
                        blank=True,
                        help_text="ex. (85)98888-8675",
                        max_length=15,
                        verbose_name="Celular2",
                    ),
                ),
                (
                    "foneCelular3",
                    models.CharField(
                        blank=True,
                        help_text="ex. (85)98888-8675",
                        max_length=15,
                        verbose_name="Celular3",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, help_text="ex. (85)98888-8675", max_length=15
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, help_text="ex. fb.com/nomenofacebook", max_length=50
                    ),
                ),
                ("twitter", models.CharField(blank=True, max_length=50)),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Endereço"
                    ),
                ),
                (
                    "enderecoNumero",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nº Endereço"
                    ),
                ),
                (
                    "enderecoComplemento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Complemento"
                    ),
                ),
                ("bairro", models.CharField(blank=True, max_length=40)),
                (
                    "cidade",
                    models.CharField(blank=True, default="Teresina", max_length=50),
                ),
                ("estado", models.CharField(blank=True, default="PI", max_length=2)),
                ("CEP", models.CharField(blank=True, max_length=12)),
                (
                    "observacao",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Observação",
                    ),
                ),
                (
                    "dataCadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Cadastrado em"
                    ),
                ),
                (
                    "pergunta",
                    models.TextField(
                        blank=True, max_length=50, null=True, verbose_name="Pergunta"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "pendente",
                    models.BooleanField(default=True, verbose_name="Pendente"),
                ),
                (
                    "termos_de_aceite",
                    models.BooleanField(
                        default=False,
                        verbose_name="Termos de aceite para tratamento de dados pessoais",
                    ),
                ),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rel_cadastrado_por",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cadastrado Por",
                    ),
                ),
                (
                    "posto_trabalho",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="participante.postotrabalho",
                        verbose_name="Posto de trabalho",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroJornada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "horario_inicio",
                    models.DateTimeField(
                        help_text="Data e hora de início da jornada.",
                        verbose_name="Horário de Início",
                    ),
                ),
                (
                    "horario_fim",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora de término da jornada (opcional).",
                        null=True,
                        verbose_name="Horário de Fim",
                    ),
                ),
                (
                    "ultimo_update",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "posto_trabalho",
                    models.ForeignKey(
                        blank=True,
                        help_text="Posto de trabalho selecionado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="participante.postotrabalho",
                        verbose_name="Posto de Trabalho",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuário ao qual a jornada pertence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_jornada",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Jornada",
                "verbose_name_plural": "Registros de Jornada",
            },
        ),
        migrations.CreateModel(
            name="DocumentoFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendedor",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Nome do Vendedor",
                    ),
                ),
                (
                    "numeroDocumento",
                    models.CharField(max_length=50, verbose_name="Número do Documento"),
                ),
                (
                    "dataDocumento",
                    models.DateField(
                        validators=[participante.models.validate_promotional_period],
                        verbose_name="Data do Documento",
                    ),
                ),
                (
                    "valorDocumento",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(
                                50,
                                message="O valor do documento deve ser maior que R$ 50,00 reais!",
                            )
                        ],
                        verbose_name="Valor do Documento",
                    ),
                ),
                (
                    "compradoREDE",
                    models.BooleanField(
                        default=False, verbose_name="Comprou na maquininha da PagBank?"
                    ),
                ),
                (
                    "compradoMASTERCARD",
                    models.BooleanField(default=False, verbose_name="Comprou com Elo?"),
                ),
                (
                    "compradoCielo",
                    models.BooleanField(
                        default=False, verbose_name="Comprou com Cielo?"
                    ),
                ),
                (
                    "valorCielo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valor pago na Cielo",
                    ),
                ),
                (
                    "valorREDE",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=7,
                        verbose_name="Valor na REDE",
                    ),
                ),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        upload_to="docs/%Y/%m/%d",
                        verbose_name="Foto do documento fiscal",
                    ),
                ),
                (
                    "photo2",
                    models.FileField(
                        blank=True,
                        upload_to="docs2/%Y/%m/%d",
                        verbose_name="Foto do comprovante do cartão",
                    ),
                ),
                (
                    "valorMASTERCARD",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=7,
                        verbose_name="Valor no MASTERCARD",
                    ),
                ),
                (
                    "valorVirtual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=20,
                        verbose_name="Valor com Bonificações",
                    ),
                ),
                (
                    "dataCadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Cadastrado em"
                    ),
                ),
                ("status", models.BooleanField(default=False, verbose_name="Status")),
                (
                    "pendente",
                    models.BooleanField(default=True, verbose_name="Pendente"),
                ),
                (
                    "observacao",
                    models.TextField(
                        blank=True,
                        default="Nenhuma",
                        max_length=1000,
                        null=True,
                        verbose_name="Observação",
                    ),
                ),
                (
                    "qtdeCupom",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "enviado_por_operador",
                    models.BooleanField(
                        default=False, verbose_name="Enviado por operador"
                    ),
                ),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cadastrado Por",
                    ),
                ),
                (
                    "lojista",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rel_lojista",
                        to="lojista.lojista",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rel_username",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "posto_trabalho",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="participante.postotrabalho",
                        verbose_name="Posto de Trabalho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Fiscal",
                "verbose_name_plural": "Documentos Fiscais",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("numeroDocumento", "lojista"),
                        name="unique_user_numeroDocumento_lojista",
                    )
                ],
            },
        ),
    ]
