# Generated by Django 5.2.4 on 2025-07-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0003_fix_cpf_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="campanha",
            name="banner_hero",
            field=models.ImageField(
                blank=True,
                help_text="Imagem principal da página inicial.",
                null=True,
                upload_to="campanhas/banners/",
            ),
        ),
        migrations.AddField(
            model_name="campanha",
            name="cor_hover",
            field=models.CharField(
                default="#1A4A2E",
                help_text="Cor para o estado 'hover' dos botões (formato HEX).",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="campanha",
            name="cor_primaria",
            field=models.CharField(
                default="#2B5C3F",
                help_text="Cor principal para botões e links (formato HEX, ex: #FF5733).",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="campanha",
            name="logo_principal",
            field=models.ImageField(
                blank=True,
                help_text="Logo que aparecerá na barra de navegação.",
                null=True,
                upload_to="campanhas/logos/",
            ),
        ),
    ]
