# Generated by Django 5.2.4 on 2025-07-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0004_campanha_banner_hero_campanha_cor_hover_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentofiscal",
            name="valorDocumento",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Valor do Documento",
            ),
        ),
    ]
