# Generated by Django 5.2.4 on 2025-07-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0006_alter_documentofiscal_valorcielo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentofiscal",
            name="pendente",
        ),
        migrations.AlterField(
            model_name="documentofiscal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("validado", "Validado"),
                    ("inconsistente", "Inconsistente"),
                ],
                default="pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
