# Generated by Django 5.2.4 on 2025-07-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0007_remove_documentofiscal_pendente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentofiscal",
            name="corrigido_pelo_participante",
            field=models.BooleanField(
                default=False, verbose_name="Corrigido pelo participante"
            ),
        ),
    ]
