# Generated by Django 5.2.4 on 2025-07-28 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0008_documentofiscal_corrigido_pelo_participante"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentofiscal",
            name="corrigido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_corrigidos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Corrigido por",
            ),
        ),
    ]
