# Generated by Django 5.2.4 on 2025-08-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0009_documentofiscal_corrigido_por"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentofiscal",
            name="corrigido_por",
        ),
        migrations.AlterField(
            model_name="documentofiscal",
            name="valorCielo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Valor pago na Cielo",
            ),
        ),
    ]
