# Generated by Django 5.2.4 on 2025-08-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0010_convert_valor_cielo_null_to_zero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentofiscal",
            name="valorCielo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=15,
                null=True,
                verbose_name="Valor pago na Cielo",
            ),
        ),
    ]
