# Generated by Django 5.2.4 on 2025-08-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0011_fix_valorcielo_null_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentofiscal",
            name="valorOutros",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=15,
                null=True,
                verbose_name="Valor pago em outros métodos",
            ),
        ),
    ]
