# Generated by Django 5.2.4 on 2025-08-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0012_documentofiscal_valoroutros"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="foneCelular1",
            field=models.CharField(
                blank=True,
                help_text="ex. (85)98888-8675",
                max_length=20,
                verbose_name="Celular1",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="foneCelular2",
            field=models.CharField(
                blank=True,
                help_text="ex. (85)98888-8675",
                max_length=20,
                verbose_name="Celular2",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="foneCelular3",
            field=models.CharField(
                blank=True,
                help_text="ex. (85)98888-8675",
                max_length=20,
                verbose_name="Celular3",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="foneFixo",
            field=models.CharField(
                blank=True,
                help_text="ex. (85)3212-0000",
                max_length=20,
                verbose_name="Telefone Fixo",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="whatsapp",
            field=models.CharField(
                blank=True, help_text="ex. (85)98888-8675", max_length=20
            ),
        ),
    ]
