# Generated by Django 5.2.4 on 2025-08-09 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0015_add_dashboard_cards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoJornada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex: Manhã, Tarde, Noite, Integral",
                        max_length=100,
                        verbose_name="Nome da Jornada",
                    ),
                ),
                (
                    "hora_inicio",
                    models.TimeField(
                        help_text="Horário de início da jornada",
                        verbose_name="Horário de Início",
                    ),
                ),
                (
                    "hora_fim",
                    models.TimeField(
                        help_text="Horário de fim da jornada",
                        verbose_name="Horário de Fim",
                    ),
                ),
                (
                    "dias_semana",
                    models.JSONField(
                        default=list,
                        help_text="Lista com números dos dias: 1=Segunda, 2=Terça, ..., 7=Domingo",
                        verbose_name="Dias da Semana",
                    ),
                ),
                (
                    "tolerancia_entrada",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Minutos de tolerância antes do horário de início",
                        verbose_name="Tolerância Entrada (min)",
                    ),
                ),
                (
                    "tolerancia_saida",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Minutos de tolerância após o horário de fim",
                        verbose_name="Tolerância Saída (min)",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Se esta jornada está ativa para uso",
                        verbose_name="Ativo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Jornada",
                "verbose_name_plural": "Tipos de Jornada",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="JornadaColaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(
                        help_text="A partir de quando esta jornada vale para o colaborador",
                        verbose_name="Data de Início",
                    ),
                ),
                (
                    "data_fim",
                    models.DateField(
                        blank=True,
                        help_text="Até quando esta jornada vale (deixe vazio para indefinido)",
                        null=True,
                        verbose_name="Data de Fim",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Se esta atribuição está ativa",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Observações sobre esta atribuição de jornada",
                        verbose_name="Observações",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jornadas_atribuidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "tipo_jornada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colaboradores",
                        to="participante.tipojornada",
                        verbose_name="Tipo de Jornada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jornada do Colaborador",
                "verbose_name_plural": "Jornadas dos Colaboradores",
                "ordering": ["-data_inicio"],
                "unique_together": {("colaborador", "data_inicio")},
            },
        ),
    ]
