# Generated by Django 5.2.4 on 2025-08-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0016_add_jornada_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_colaborador",
            field=models.BooleanField(
                default=False,
                help_text="Define se este usuário é um colaborador (equipe interna) ou participante comum",
                verbose_name="É Colaborador",
            ),
        ),
    ]
