# Generated by Django 5.2.4 on 2025-08-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0017_add_is_colaborador_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jornadacolaborador",
            options={
                "ordering": ["-data_inicio"],
                "permissions": [
                    ("atribuir_jornada", "Pode atribuir jornadas a colaboradores"),
                    ("editar_atribuicao", "Pode editar atribuições de jornada"),
                    ("remover_atribuicao", "Pode remover atribuições de jornada"),
                    (
                        "visualizar_atribuicoes",
                        "Pode visualizar atribuições de jornada",
                    ),
                ],
                "verbose_name": "Jornada do Colaborador",
                "verbose_name_plural": "Jornadas dos Colaboradores",
            },
        ),
        migrations.AlterModelOptions(
            name="tipojornada",
            options={
                "ordering": ["nome"],
                "permissions": [
                    ("criar_jornada", "Pode criar tipos de jornada"),
                    ("editar_jornada", "Pode editar tipos de jornada"),
                    ("excluir_jornada", "Pode excluir tipos de jornada"),
                    ("visualizar_jornada", "Pode visualizar tipos de jornada"),
                ],
                "verbose_name": "Tipo de Jornada",
                "verbose_name_plural": "Tipos de Jornada",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="senha_temporaria",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o usuário precisa trocar a senha no próximo login",
                verbose_name="Senha Temporária",
            ),
        ),
        migrations.AlterField(
            model_name="systempermission",
            name="category",
            field=models.CharField(
                choices=[
                    ("dashboard", "Dashboard"),
                    ("documents", "Documentos"),
                    ("stores", "Lojistas"),
                    ("system", "Sistema"),
                    ("jornadas", "Jornadas de Trabalho"),
                ],
                max_length=50,
            ),
        ),
    ]
