# Generated by Django 5.2.4 on 2025-08-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0018_alter_jornadacolaborador_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="status_ativo",
            field=models.BooleanField(
                default=True,
                help_text="Para colaboradores: indica se o cadastro está ativo e configurado",
                verbose_name="Status Ativo",
            ),
        ),
    ]
