# Generated by Django 4.2.23 on 2025-08-15 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("participante", "0019_profile_status_ativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="jornada_flexivel",
            field=models.BooleanField(
                default=False,
                help_text="Permite entrada/saída sem horário fixo",
                verbose_name="Jornada flexível",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="requer_jornada",
            field=models.BooleanField(
                default=True,
                help_text="Se este usuário precisa de controle de jornada",
                verbose_name="Requer controle de jornada",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="ultima_jornada_data",
            field=models.DateField(
                blank=True,
                help_text="Data do último registro de jornada",
                null=True,
                verbose_name="Data da última jornada",
            ),
        ),
        migrations.AddField(
            model_name="registrojornada",
            name="finalizada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jornadas_finalizadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Finalizada por",
            ),
        ),
        migrations.AddField(
            model_name="registrojornada",
            name="observacoes",
            field=models.TextField(
                blank=True,
                help_text="Observações sobre esta jornada",
                verbose_name="Observações",
            ),
        ),
        migrations.AddField(
            model_name="registrojornada",
            name="status",
            field=models.CharField(
                choices=[
                    ("ATIVA", "Ativa"),
                    ("FINALIZADA", "Finalizada"),
                    ("PAUSA", "Em Pausa"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="ATIVA",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="ExcecaoJornada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SEM_JORNADA", "Sem controle de jornada"),
                            ("JORNADA_FLEXIVEL", "Jornada flexível"),
                            ("HORARIO_ESPECIAL", "Horário especial"),
                            ("FERIADO", "Feriado/Evento"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Exceção",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                (
                    "data_fim",
                    models.DateField(
                        blank=True,
                        help_text="Deixe vazio para exceção permanente",
                        null=True,
                        verbose_name="Data de Fim",
                    ),
                ),
                (
                    "horario_inicio",
                    models.TimeField(
                        blank=True,
                        help_text="Para horários especiais",
                        null=True,
                        verbose_name="Horário de Início",
                    ),
                ),
                (
                    "horario_fim",
                    models.TimeField(
                        blank=True,
                        help_text="Para horários especiais",
                        null=True,
                        verbose_name="Horário de Fim",
                    ),
                ),
                (
                    "justificativa",
                    models.TextField(
                        help_text="Motivo da exceção", verbose_name="Justificativa"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="excecoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excecoes_jornada",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exceção de Jornada",
                "verbose_name_plural": "Exceções de Jornada",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoJornada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requer_jornada",
                    models.BooleanField(
                        default=True,
                        help_text="Se este grupo precisa de controle de jornada",
                        verbose_name="Requer controle de jornada",
                    ),
                ),
                (
                    "jornada_flexivel",
                    models.BooleanField(
                        default=False,
                        help_text="Permite entrada/saída sem horário fixo",
                        verbose_name="Jornada flexível",
                    ),
                ),
                (
                    "tolerancia_entrada",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Minutos de tolerância antes do horário de início",
                        verbose_name="Tolerância entrada (min)",
                    ),
                ),
                (
                    "tolerancia_saida",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Minutos de tolerância após o horário de fim",
                        verbose_name="Tolerância saída (min)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        help_text="Grupo de usuários afetado por esta configuração",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                        verbose_name="Grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Jornada",
                "verbose_name_plural": "Configurações de Jornada",
                "unique_together": {("grupo",)},
            },
        ),
    ]
