# Generated by Django 4.2.23 on 2025-08-15 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "participante",
            "0020_profile_jornada_flexivel_profile_requer_jornada_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chave",
                    models.CharField(max_length=100, unique=True, verbose_name="Chave"),
                ),
                ("valor", models.TextField(verbose_name="Valor")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TEXT", "Texto"),
                            ("NUMBER", "Número"),
                            ("BOOLEAN", "Booleano"),
                            ("JSON", "JSON"),
                            ("URL", "URL"),
                        ],
                        default="TEXT",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração do Sistema",
                "verbose_name_plural": "Configurações do Sistema",
                "ordering": ["chave"],
            },
        ),
        migrations.CreateModel(
            name="Funcionalidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, verbose_name="Nome da Funcionalidade"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código único"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("VIEW", "Visualizar"),
                            ("CREATE", "Criar"),
                            ("EDIT", "Editar"),
                            ("DELETE", "Excluir"),
                            ("EXPORT", "Exportar"),
                            ("IMPORT", "Importar"),
                            ("PRINT", "Imprimir"),
                            ("VALIDATE", "Validar"),
                            ("APPROVE", "Aprovar"),
                            ("REJECT", "Rejeitar"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Modelo relacionado"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grupos_permitidos",
                    models.ManyToManyField(
                        blank=True, to="auth.group", verbose_name="Grupos permitidos"
                    ),
                ),
                (
                    "usuarios_excluidos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="funcionalidades_excluidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuários excluídos",
                    ),
                ),
                (
                    "usuarios_permitidos",
                    models.ManyToManyField(
                        blank=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuários permitidos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionalidade",
                "verbose_name_plural": "Funcionalidades",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="CardDinamico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome do Card")),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("STATS", "Estatísticas"),
                            ("FUNCIONALIDADE", "Funcionalidade"),
                            ("RELATORIO", "Relatório"),
                            ("SISTEMA", "Sistema"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        choices=[
                            ("fas fa-chart-bar", "Gráfico"),
                            ("fas fa-file-alt", "Documento"),
                            ("fas fa-users", "Usuários"),
                            ("fas fa-store", "Loja"),
                            ("fas fa-ticket-alt", "Cupom"),
                            ("fas fa-clock", "Jornada"),
                            ("fas fa-cog", "Configuração"),
                            ("fas fa-chart-line", "Relatório"),
                            ("fas fa-database", "Dados"),
                            ("fas fa-tools", "Ferramentas"),
                            ("fas fa-eye", "Visualizar"),
                            ("fas fa-edit", "Editar"),
                            ("fas fa-plus", "Adicionar"),
                            ("fas fa-trash", "Excluir"),
                            ("fas fa-download", "Download"),
                            ("fas fa-upload", "Upload"),
                            ("fas fa-print", "Imprimir"),
                            ("fas fa-search", "Buscar"),
                            ("fas fa-filter", "Filtrar"),
                            ("fas fa-sort", "Ordenar"),
                        ],
                        max_length=50,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        default="primary", max_length=20, verbose_name="Cor"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="URL de destino"
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de exibição"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "mostrar_apenas_admin",
                    models.BooleanField(
                        default=False, verbose_name="Mostrar apenas para admin"
                    ),
                ),
                (
                    "mostrar_apenas_staff",
                    models.BooleanField(
                        default=False, verbose_name="Mostrar apenas para staff"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grupos_permitidos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Deixe vazio para permitir todos os grupos",
                        to="auth.group",
                        verbose_name="Grupos permitidos",
                    ),
                ),
                (
                    "usuarios_excluidos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Usuários específicos que NÃO podem ver este card",
                        related_name="cards_excluidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuários excluídos",
                    ),
                ),
                (
                    "usuarios_permitidos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Usuários específicos que podem ver este card",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuários permitidos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Dinâmico",
                "verbose_name_plural": "Cards Dinâmicos",
                "ordering": ["ordem", "nome"],
            },
        ),
    ]
