# Generated by Django 4.2.23 on 2025-08-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0021_configuracaosistema_funcionalidade_carddinamico"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoSecao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("participantes", "Participantes"),
                            ("lojistas", "Lojistas"),
                            ("configuracoes", "Configurações"),
                            ("backoffice", "Backoffice"),
                            ("relatorios", "Relatórios"),
                            ("usuarios", "Usuários"),
                            ("operacoes", "Operações"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Tipo da Seção",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=100, verbose_name="Título da Seção"),
                ),
                (
                    "icone",
                    models.CharField(
                        help_text="Código FontAwesome (ex: fas fa-users)",
                        max_length=50,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        choices=[
                            ("primary", "Azul Primário"),
                            ("info", "Azul Claro"),
                            ("secondary", "Cinza"),
                            ("success", "Verde"),
                            ("warning", "Amarelo"),
                            ("danger", "Vermelho"),
                            ("light", "Branco"),
                            ("dark", "Preto"),
                        ],
                        default="primary",
                        max_length=20,
                        verbose_name="Cor do Cabeçalho",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Seção Ativa"),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Seção",
                "verbose_name_plural": "Configurações de Seções",
                "ordering": ["ordem", "tipo"],
            },
        ),
    ]
