# Generated by Django 4.2.23 on 2025-08-16 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("participante", "0022_configuracaosecao"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosecao",
            name="grupos_permitidos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Deixe vazio para permitir todos os grupos",
                to="auth.group",
                verbose_name="Grupos que podem ver esta seção",
            ),
        ),
        migrations.AlterField(
            model_name="carddinamico",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PARTICIPANTE", "Participante"),
                    ("LOJISTA", "Lojista"),
                    ("RECURSOS_HUMANOS", "Recursos Humanos"),
                    ("BACKOFFICE", "Backoffice"),
                    ("RELATORIO", "Relatório"),
                    ("CONFIGURACAO", "Configuração"),
                    ("OPERACOES", "Operações"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.CreateModel(
            name="URLTreinamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash_url",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Hash da URL"
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=100, verbose_name="Título do Treinamento"
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("ativo", models.BooleanField(default=True, verbose_name="URL Ativa")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "colaboradores_cadastrados",
                    models.ManyToManyField(
                        blank=True,
                        to="participante.profile",
                        verbose_name="Colaboradores Cadastrados",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "URL de Treinamento",
                "verbose_name_plural": "URLs de Treinamento",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
