# Generated by Django 4.2.23 on 2025-08-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0023_configuracaosecao_grupos_permitidos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carddinamico",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PARTICIPANTES", "Participantes"),
                    ("LOJISTAS", "Lojistas"),
                    ("RECURSOS_HUMANOS", "Recursos Humanos"),
                    ("BACKOFFICE", "Backoffice"),
                    ("RELATORIOS", "Relatórios"),
                    ("CONFIGURACOES", "Configurações"),
                    ("OPERACOES", "Operações"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="configuracaosecao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PARTICIPANTES", "Participantes"),
                    ("LOJISTAS", "Lojistas"),
                    ("RECURSOS_HUMANOS", "Recursos Humanos"),
                    ("BACKOFFICE", "Backoffice"),
                    ("RELATORIOS", "Relatórios"),
                    ("CONFIGURACOES", "Configurações"),
                    ("OPERACOES", "Operações"),
                ],
                max_length=20,
                unique=True,
                verbose_name="Tipo da Seção",
            ),
        ),
    ]
