# Generated by Django 4.2.23 on 2025-08-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0026_remove_cores_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carddinamico",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PARTICIPANTE", "Participante"),
                    ("LOJISTA", "Lojista"),
                    ("RECURSOS_HUMANOS", "Recursos Humanos"),
                    ("BACKOFFICE", "Backoffice"),
                    ("RELATORIO", "Relatório"),
                    ("CONFIGURACAO", "Configuração"),
                    ("OPERACOES", "Operações"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="configuracaosecao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("participantes", "Participantes"),
                    ("lojistas", "Lojistas"),
                    ("configuracoes", "Configurações"),
                    ("backoffice", "Backoffice"),
                    ("relatorios", "Relatórios"),
                    ("usuarios", "Usuários"),
                    ("operacoes", "Operações"),
                ],
                max_length=20,
                unique=True,
                verbose_name="Tipo da Seção",
            ),
        ),
    ]
