# Generated by Django 4.2.23 on 2025-08-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0027_alter_carddinamico_tipo_alter_configuracaosecao_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaosecao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PARTICIPANTE", "Participante"),
                    ("LOJISTA", "Lojista"),
                    ("RECURSOS_HUMANOS", "Recursos Humanos"),
                    ("BACKOFFICE", "Backoffice"),
                    ("RELATORIO", "Relatório"),
                    ("CONFIGURACAO", "Configuração"),
                    ("OPERACOES", "Operações"),
                ],
                max_length=20,
                unique=False,
                verbose_name="Tipo da Seção",
            ),
        ),
    ]
