# Generated by Django 4.2.23 on 2025-08-17 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0028_remove_tipo_unique_constraint"),
    ]

    operations = []
