# Generated by Django 4.2.23 on 2025-08-17 04:41

from django.db import migrations


def update_secao_tipos_simple(apps, schema_editor):
    """Atualiza os tipos de seção para os novos valores"""
    ConfiguracaoSecao = apps.get_model('participante', 'ConfiguracaoSecao')
    
    # Mapeamento dos tipos antigos para os novos
    tipo_mapping = {
        'participantes': 'PARTICIPANTE',
        'lojistas': 'LOJISTA',
        'configuracoes': 'CONFIGURACAO',
        'backoffice': 'BACKOFFICE',
        'relatorios': 'RELATORIO',
        'usuarios': 'RECURSOS_HUMANOS',
        'operacoes': 'OPERACOES',
    }
    
    # Atualizar cada seção
    for secao in ConfiguracaoSecao.objects.all():
        if secao.tipo in tipo_mapping:
            secao.tipo = tipo_mapping[secao.tipo]
            secao.save()


def reverse_update_secao_tipos_simple(apps, schema_editor):
    """Reverte os tipos de seção para os valores antigos"""
    ConfiguracaoSecao = apps.get_model('participante', 'ConfiguracaoSecao')
    
    # Mapeamento reverso
    tipo_mapping_reverse = {
        'PARTICIPANTE': 'participantes',
        'LOJISTA': 'lojistas',
        'CONFIGURACAO': 'configuracoes',
        'BACKOFFICE': 'backoffice',
        'RELATORIO': 'relatorios',
        'RECURSOS_HUMANOS': 'usuarios',
        'OPERACOES': 'operacoes',
    }
    
    # Atualizar cada seção
    for secao in ConfiguracaoSecao.objects.all():
        if secao.tipo in tipo_mapping_reverse:
            secao.tipo = tipo_mapping_reverse[secao.tipo]
            secao.save()


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0028_remove_tipo_unique_constraint"),
    ]

    operations = [
        migrations.RunPython(update_secao_tipos_simple, reverse_update_secao_tipos_simple),
    ]
