# Generated by Django 4.2.23 on 2025-08-17 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0029_update_secao_tipos_data_simple"),
        ("participante", "0030_update_secao_tipos_data_simple"),
    ]

    operations = []
