# Generated by Django 4.2.23 on 2025-08-17 04:45

from django.db import migrations


def clean_duplicate_secoes(apps, schema_editor):
    """Remove configurações de seção duplicadas, mantendo apenas uma por tipo"""
    ConfiguracaoSecao = apps.get_model('participante', 'ConfiguracaoSecao')
    
    # Para cada tipo, manter apenas a primeira configuração
    tipos_unicos = set()
    for secao in ConfiguracaoSecao.objects.all():
        if secao.tipo in tipos_unicos:
            # Já existe uma configuração para este tipo, remover esta
            secao.delete()
        else:
            # Primeira vez vendo este tipo, marcar como visto
            tipos_unicos.add(secao.tipo)


def reverse_clean_duplicate_secoes(apps, schema_editor):
    """Não é possível reverter a limpeza de duplicatas"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0031_merge_20250817_0143"),
    ]

    operations = [
        migrations.RunPython(clean_duplicate_secoes, reverse_clean_duplicate_secoes),
    ]
