# Generated by Django 4.2.23 on 2025-08-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0032_clean_duplicate_secoes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaosecao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PARTICIPANTE", "Participante"),
                    ("LOJISTA", "Lojista"),
                    ("RECURSOS_HUMANOS", "Recursos Humanos"),
                    ("BACKOFFICE", "Backoffice"),
                    ("RELATORIO", "Relatório"),
                    ("CONFIGURACAO", "Configuração"),
                    ("OPERACOES", "Operações"),
                ],
                max_length=20,
                unique=True,
                verbose_name="Tipo da Seção",
            ),
        ),
    ]
