# Generated by Django 4.2.23 on 2025-08-24 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("participante", "0033_alter_configuracaosecao_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReversaoImpressao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_reversao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da reversão"
                    ),
                ),
                (
                    "cupons_removidos",
                    models.PositiveIntegerField(
                        verbose_name="Quantidade de cupons removidos"
                    ),
                ),
                (
                    "motivo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo da reversão"
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reversoes_impressao",
                        to="participante.documentofiscal",
                        verbose_name="Documento Fiscal",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reversoes_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário que realizou a reversão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reversão de Impressão",
                "verbose_name_plural": "Reversões de Impressão",
                "ordering": ["-data_reversao"],
                "unique_together": {("documento", "usuario")},
            },
        ),
    ]
