# Generated by Django 4.2.23 on 2025-08-24 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("participante", "0034_add_reversao_impressao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data e Hora da Ação"
                    ),
                ),
                (
                    "tipo_acao",
                    models.CharField(
                        choices=[
                            ("reversao_impressao", "Reversão de Impressão"),
                            ("impressao_cupons", "Impressão de Cupons"),
                            ("validacao_documento", "Validação de Documento"),
                            ("edicao_documento", "Edição de Documento"),
                            ("cadastro_documento", "Cadastro de Documento"),
                            ("finalizacao_jornada", "Finalização de Jornada"),
                            ("selecao_posto", "Seleção de Posto de Trabalho"),
                            ("login", "Login no Sistema"),
                            ("logout", "Logout do Sistema"),
                            ("alteracao_senha", "Alteração de Senha"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Ação",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição da Ação")),
                (
                    "justificativa",
                    models.TextField(
                        blank=True, null=True, verbose_name="Justificativa da Ação"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "documento_fiscal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auditorias",
                        to="participante.documentofiscal",
                        verbose_name="Documento Fiscal Relacionado",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acoes_auditoria",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário que realizou a ação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoria",
                "verbose_name_plural": "Registros de Auditoria",
                "ordering": ["-data_hora"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "data_hora"],
                        name="participant_usuario_c2aa81_idx",
                    ),
                    models.Index(
                        fields=["tipo_acao", "data_hora"],
                        name="participant_tipo_ac_6c7072_idx",
                    ),
                    models.Index(
                        fields=["documento_fiscal", "data_hora"],
                        name="participant_documen_3cc3d4_idx",
                    ),
                ],
            },
        ),
    ]
