# Generated by Django 4.2.23 on 2025-08-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0035_auditoria"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reversaoimpressao",
            unique_together=set(),
        ),
    ]
