# Generated by Django 4.2.23 on 2025-08-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0036_alter_reversaoimpressao_unique_together"),
    ]

    operations = []
