# Generated by Django 4.2.23 on 2025-08-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0037_auto_20250824_1733"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reversaoimpressao",
            name="motivo",
            field=models.TextField(
                blank=True,
                help_text="Justificativa para a reversão",
                null=True,
                verbose_name="Motivo da reversão",
            ),
        ),
    ]
