# Generated by Django 4.2.23 on 2025-08-27 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0002_fix_autorizar_lojista_permissions"),
        ("participante", "0038_alter_reversaoimpressao_motivo"),
    ]

    operations = []
