# Generated by Django 4.2.23 on 2025-08-27 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("participante", "0039_merge_20250827_0152"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditoria",
            name="tipo_acao",
            field=models.CharField(
                choices=[
                    ("reversao_impressao", "Reversão de Impressão"),
                    ("cancelamento_impressao", "Cancelamento de Impressão"),
                    ("impressao_cupons", "Impressão de Cupons"),
                    ("validacao_documento", "Validação de Documento"),
                    ("edicao_documento", "Edição de Documento"),
                    ("cadastro_documento", "Cadastro de Documento"),
                    ("finalizacao_jornada", "Finalização de Jornada"),
                    ("selecao_posto", "Seleção de Posto de Trabalho"),
                    ("login", "Login no Sistema"),
                    ("logout", "Logout do Sistema"),
                    ("alteracao_senha", "Alteração de Senha"),
                    ("outro", "Outro"),
                ],
                max_length=50,
                verbose_name="Tipo de Ação",
            ),
        ),
        migrations.CreateModel(
            name="CancelamentoImpressao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_cancelamento",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do cancelamento"
                    ),
                ),
                (
                    "motivo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo do cancelamento"
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancelamentos_impressao",
                        to="participante.documentofiscal",
                        verbose_name="Documento Fiscal",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancelamentos_realizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário que realizou o cancelamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cancelamento de Impressão",
                "verbose_name_plural": "Cancelamentos de Impressão",
                "ordering": ["-data_cancelamento"],
            },
        ),
    ]
