# Generated by Django 5.2.8 on 2025-12-09 01:21

import liquida2018.storage_backends
import participante.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0040_alter_auditoria_tipo_acao_cancelamentoimpressao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='banner_hero',
            field=models.ImageField(blank=True, help_text='Imagem principal da página inicial.', null=True, storage=liquida2018.storage_backends.MediaStorage(), upload_to='campanhas/banners/'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='logo_principal',
            field=models.ImageField(blank=True, help_text='Logo que aparecerá na barra de navegação.', null=True, storage=liquida2018.storage_backends.MediaStorage(), upload_to='campanhas/logos/'),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='dataDocumento',
            field=models.DateField(validators=[participante.models.validate_promotional_period, participante.models.validate_data_futura], verbose_name='Data do Documento'),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='photo',
            field=models.FileField(blank=True, storage=liquida2018.storage_backends.MediaStorage(), upload_to='docs/%Y/%m/%d', verbose_name='Foto do documento fiscal'),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='photo2',
            field=models.FileField(blank=True, storage=liquida2018.storage_backends.MediaStorage(), upload_to='docs2/%Y/%m/%d', verbose_name='Foto do comprovante do cartão'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, storage=liquida2018.storage_backends.MediaStorage(), upload_to='users/%Y/%m/%d'),
        ),
    ]
