# Generated by Django 5.2.8 on 2026-06-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participante", "0041_alter_campanha_banner_hero_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="permissoes_adicionais",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permissões explicitamente concedidas a este usuário",
                related_name="perfis_adicionais",
                to="participante.systempermission",
                verbose_name="Permissões Adicionais",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="permissoes_excluidas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permissões explicitamente revogadas para este usuário",
                related_name="perfis_excluidos",
                to="participante.systempermission",
                verbose_name="Permissões Excluídas",
            ),
        ),
        migrations.AlterField(
            model_name="campanha",
            name="banner_hero",
            field=models.ImageField(
                blank=True,
                help_text="Imagem principal da página inicial.",
                null=True,
                upload_to="campanhas/banners/",
            ),
        ),
        migrations.AlterField(
            model_name="campanha",
            name="logo_principal",
            field=models.ImageField(
                blank=True,
                help_text="Logo que aparecerá na barra de navegação.",
                null=True,
                upload_to="campanhas/logos/",
            ),
        ),
        migrations.AlterField(
            model_name="documentofiscal",
            name="photo",
            field=models.FileField(
                blank=True,
                upload_to="docs/%Y/%m/%d",
                verbose_name="Foto do documento fiscal",
            ),
        ),
        migrations.AlterField(
            model_name="documentofiscal",
            name="photo2",
            field=models.FileField(
                blank=True,
                upload_to="docs2/%Y/%m/%d",
                verbose_name="Foto do comprovante do cartão",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, upload_to="users/%Y/%m/%d"),
        ),
    ]
